
// ******************************************************
// Copyright (c) 2026 Sidata Solusi Ritel
// Licensed under the MIT License.
// build by Claude Code, Edo Suhartanto 
// ******************************************************

using System.Text;
using System.Text.Json;

/// <summary>
/// SwaggerToHttp - Konverter swagger.json ke file .http
/// Dijalankan sebagai post-build tool pada proyek ASP.NET Core 8
/// </summary>
class Program
{
    static int Main(string[] args)
    {
        Console.WriteLine("=== SwaggerToHttp Converter ===");

        // Tentukan path swagger.json dan output .http
        string swaggerPath = ResolveSwaggerPath(args);
        string outputPath = ResolveOutputPath(args, swaggerPath);

        if (!File.Exists(swaggerPath))
        {
            Console.WriteLine($"[SKIP] swagger.json tidak ditemukan: {swaggerPath}");
            Console.WriteLine("       Pastikan aplikasi sudah dijalankan minimal sekali agar Swagger di-generate.");
            return 0; // Tidak error, cukup skip
        }

        try
        {
            string json = File.ReadAllText(swaggerPath);
            var doc = JsonDocument.Parse(json);
            string content = GenerateHttpFile(doc);

            File.WriteAllText(outputPath, content, Encoding.UTF8);
            Console.WriteLine($"[OK] File .http berhasil dibuat: {outputPath}");
            return 0;
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"[ERROR] {ex.Message}");
            return 1;
        }
    }

    // -------------------------------------------------------------------------
    // Path Resolution
    // -------------------------------------------------------------------------

    static string ResolveSwaggerPath(string[] args)
    {
        // Argumen pertama = path swagger.json (opsional)
        if (args.Length > 0 && args[0].EndsWith(".json", StringComparison.OrdinalIgnoreCase))
            return Path.GetFullPath(args[0]);

        // Default: cari di direktori kerja saat ini
        string[] candidates =
        [
            Path.Combine(Directory.GetCurrentDirectory(), "swagger.json"),
            Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "swagger", "v1", "swagger.json"),
            Path.Combine(Directory.GetCurrentDirectory(), "obj", "swagger.json"),
        ];

        foreach (var c in candidates)
            if (File.Exists(c)) return c;

        return candidates[0]; // Kembalikan default meski tidak ada (akan di-handle caller)
    }

    static string ResolveOutputPath(string[] args, string swaggerPath)
    {
        // Argumen kedua = path output .http (opsional)
        if (args.Length > 1 && args[1].EndsWith(".http", StringComparison.OrdinalIgnoreCase))
            return Path.GetFullPath(args[1]);

        // Default: letakkan di direktori yang sama dengan swagger.json, nama "requests.http"
        string dir = Path.GetDirectoryName(swaggerPath) ?? Directory.GetCurrentDirectory();
        string name = Path.GetFileNameWithoutExtension(swaggerPath); // biasanya "swagger"
        return Path.Combine(dir, $"{name}.http");
    }

    // -------------------------------------------------------------------------
    // Generator utama
    // -------------------------------------------------------------------------

    static string GenerateHttpFile(JsonDocument doc)
    {
        var sb = new StringBuilder();
        var root = doc.RootElement;

        // --- Header file ---
        string title = root.TryGetProperty("info", out var info)
                         && info.TryGetProperty("title", out var t) ? t.GetString() ?? "API" : "API";
        string version = info.TryGetProperty("version", out var v) ? v.GetString() ?? "1.0" : "1.0";
        string baseUrl = ResolveBaseUrl(root);

        sb.AppendLine($"### {title} v{version}");
        sb.AppendLine($"### Auto-generated by SwaggerToHttp pada {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine();
        sb.AppendLine("# ============================================================");
        sb.AppendLine("# Variabel global — ubah sesuai environment");
        sb.AppendLine("# ============================================================");
        sb.AppendLine($"@baseUrl = {baseUrl}");
        sb.AppendLine("@contentType = application/json");
        sb.AppendLine();

        // Kumpulkan token auth jika ada security scheme
        bool hasBearer = HasBearerAuth(root);
        if (hasBearer)
        {
            sb.AppendLine("# Isi token setelah login");
            sb.AppendLine("@authToken = YOUR_JWT_TOKEN_HERE");
            sb.AppendLine();
        }

        // --- Paths ---
        if (!root.TryGetProperty("paths", out var paths))
        {
            sb.AppendLine("# Tidak ada path yang ditemukan di swagger.json");
            return sb.ToString();
        }

        // Kelompokkan per tag
        var groups = new SortedDictionary<string, List<(string path, string method, JsonElement op)>>(
                         StringComparer.OrdinalIgnoreCase);

        foreach (var pathItem in paths.EnumerateObject())
        {
            foreach (var methodItem in pathItem.Value.EnumerateObject())
            {
                string httpMethod = methodItem.Name.ToUpperInvariant();
                if (httpMethod is not ("GET" or "POST" or "PUT" or "PATCH" or "DELETE" or "HEAD" or "OPTIONS"))
                    continue;

                string tag = GetFirstTag(methodItem.Value);
                if (!groups.TryGetValue(tag, out var list))
                    groups[tag] = list = [];
                list.Add((pathItem.Name, httpMethod, methodItem.Value));
            }
        }

        // Resolve schemas untuk body generation
        var schemas = ResolveSchemas(root);

        foreach (var (tag, operations) in groups)
        {
            sb.AppendLine($"# ============================================================");
            sb.AppendLine($"# {tag}");
            sb.AppendLine($"# ============================================================");
            sb.AppendLine();

            foreach (var (path, method, op) in operations)
            {
                AppendOperation(sb, path, method, op, baseUrl, hasBearer, schemas, root);
            }
        }

        return sb.ToString();
    }

    // -------------------------------------------------------------------------
    // Operasi tunggal
    // -------------------------------------------------------------------------

    static void AppendOperation(
        StringBuilder sb,
        string path,
        string method,
        JsonElement op,
        string baseUrl,
        bool hasBearer,
        Dictionary<string, JsonElement> schemas,
        JsonElement root)
    {
        string summary = op.TryGetProperty("summary", out var s) ? s.GetString() ?? "" : "";
        string opId = op.TryGetProperty("operationId", out var oid) ? oid.GetString() ?? "" : "";
        bool secured = IsOperationSecured(op, root);

        // Komentar deskripsi
        if (!string.IsNullOrWhiteSpace(summary))
            sb.AppendLine($"### {summary}");
        else
            sb.AppendLine($"### {method} {path}");

        if (!string.IsNullOrWhiteSpace(opId))
            sb.AppendLine($"# operationId: {opId}");

        // Bangun URL dengan path params
        string urlPath = BuildUrlPath(path, op);

        // Query params
        string query = BuildQueryString(op);

        sb.Append($"{method} {{{{baseUrl}}}}{urlPath}");
        if (!string.IsNullOrEmpty(query)) sb.Append(query);
        sb.AppendLine();

        sb.AppendLine("Content-Type: {{contentType}}");

        if (secured && hasBearer)
            sb.AppendLine("Authorization: Bearer {{authToken}}");

        // Request body
        if (op.TryGetProperty("requestBody", out var reqBody))
        {
            string? bodyJson = GenerateBodyExample(reqBody, schemas);
            if (bodyJson != null)
            {
                sb.AppendLine();
                sb.AppendLine(bodyJson);
            }
        }

        sb.AppendLine();
        sb.AppendLine("###");
        sb.AppendLine();
    }

    // -------------------------------------------------------------------------
    // URL & Query helpers
    // -------------------------------------------------------------------------

    static string BuildUrlPath(string path, JsonElement op)
    {
        // Ganti {param} dengan {{param}} agar kompatibel dengan .http variable syntax
        // dan tambahkan komentar nilai contoh
        if (!op.TryGetProperty("parameters", out var parameters))
            return path;

        string result = path;
        foreach (var param in parameters.EnumerateArray())
        {
            if (!param.TryGetProperty("in", out var inProp) || inProp.GetString() != "path")
                continue;

            string? name = param.TryGetProperty("name", out var n) ? n.GetString() : null;
            if (name == null) continue;

            string example = GetParamExample(param);
            result = result.Replace($"{{{name}}}", example);
        }

        return result;
    }

    static string BuildQueryString(JsonElement op)
    {
        if (!op.TryGetProperty("parameters", out var parameters))
            return "";

        var qParams = new List<string>();
        foreach (var param in parameters.EnumerateArray())
        {
            if (!param.TryGetProperty("in", out var inProp) || inProp.GetString() != "query")
                continue;

            string? name = param.TryGetProperty("name", out var n) ? n.GetString() : null;
            if (name == null) continue;

            bool required = param.TryGetProperty("required", out var req) && req.GetBoolean();
            string example = GetParamExample(param);
            qParams.Add($"{name}={example}");

            if (!required) // Tandai opsional dengan komentar inline
            {
                // Tidak bisa komentar di dalam query string .http, jadi cukup sertakan
            }
        }

        return qParams.Count > 0 ? "?" + string.Join("&", qParams) : "";
    }

    static string GetParamExample(JsonElement param)
    {
        // Prioritas: example > schema.example > schema.default > type-based default
        if (param.TryGetProperty("example", out var ex))
            return ex.ToString();

        if (param.TryGetProperty("schema", out var schema))
        {
            if (schema.TryGetProperty("example", out var sex)) return sex.ToString();
            if (schema.TryGetProperty("default", out var def)) return def.ToString();

            string type = schema.TryGetProperty("type", out var t) ? t.GetString() ?? "string" : "string";
            return TypeDefaultValue(type, schema);
        }

        return "value";
    }

    static string TypeDefaultValue(string type, JsonElement schema) => type switch
    {
        "integer" or "number" => "1",
        "boolean" => "true",
        "array" => "item1",
        _ => "string"
    };

    // -------------------------------------------------------------------------
    // Body generation
    // -------------------------------------------------------------------------

    static string? GenerateBodyExample(JsonElement requestBody, Dictionary<string, JsonElement> schemas)
    {
        if (!requestBody.TryGetProperty("content", out var content))
            return null;

        // Cari application/json
        if (!content.TryGetProperty("application/json", out var jsonContent))
        {
            // Coba ambil konten pertama
            foreach (var c in content.EnumerateObject())
            {
                jsonContent = c.Value;
                break;
            }
        }

        if (jsonContent.ValueKind == JsonValueKind.Undefined)
            return null;

        // Coba dari examples dulu
        if (jsonContent.TryGetProperty("examples", out var examples))
        {
            foreach (var ex in examples.EnumerateObject())
            {
                if (ex.Value.TryGetProperty("value", out var val))
                    return FormatJson(val.GetRawText());
            }
        }

        if (jsonContent.TryGetProperty("example", out var directExample))
            return FormatJson(directExample.GetRawText());

        // Generate dari schema
        if (jsonContent.TryGetProperty("schema", out var schema))
        {
            var generated = GenerateFromSchema(schema, schemas, 0);
            return FormatJson(JsonSerializer.Serialize(generated, new JsonSerializerOptions { WriteIndented = true }));
        }

        return null;
    }

    static object? GenerateFromSchema(JsonElement schema, Dictionary<string, JsonElement> schemas, int depth)
    {
        if (depth > 5) return null; // Hindari rekursi tak terbatas

        // Resolve $ref
        if (schema.TryGetProperty("$ref", out var refProp))
        {
            string refStr = refProp.GetString() ?? "";
            string refName = refStr.Split('/').Last();
            if (schemas.TryGetValue(refName, out var refSchema))
                return GenerateFromSchema(refSchema, schemas, depth + 1);
            return $"<{refName}>";
        }

        // anyOf / oneOf / allOf
        foreach (string combiner in new[] { "allOf", "anyOf", "oneOf" })
        {
            if (schema.TryGetProperty(combiner, out var combined))
            {
                if (combiner == "allOf")
                {
                    // Merge semua properti
                    var merged = new Dictionary<string, object?>();
                    foreach (var sub in combined.EnumerateArray())
                    {
                        var subObj = GenerateFromSchema(sub, schemas, depth + 1);
                        if (subObj is Dictionary<string, object?> dict)
                            foreach (var kv in dict) merged[kv.Key] = kv.Value;
                    }
                    return merged;
                }
                // anyOf / oneOf: ambil yang pertama
                foreach (var sub in combined.EnumerateArray())
                    return GenerateFromSchema(sub, schemas, depth + 1);
            }
        }

        string type = schema.TryGetProperty("type", out var t) ? t.GetString() ?? "object" : "object";

        // Gunakan example / default jika ada
        if (schema.TryGetProperty("example", out var example)) return ParseJsonElement(example);
        if (schema.TryGetProperty("default", out var def)) return ParseJsonElement(def);

        return type switch
        {
            "object" => GenerateObject(schema, schemas, depth),
            "array" => GenerateArray(schema, schemas, depth),
            "string" => GenerateString(schema),
            "integer" => 1,
            "number" => 1.0,
            "boolean" => true,
            "null" => null,
            _ => GenerateObject(schema, schemas, depth)
        };
    }

    static Dictionary<string, object?> GenerateObject(JsonElement schema, Dictionary<string, JsonElement> schemas, int depth)
    {
        var result = new Dictionary<string, object?>();

        if (!schema.TryGetProperty("properties", out var props))
            return result;

        var required = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        if (schema.TryGetProperty("required", out var req))
            foreach (var r in req.EnumerateArray())
                if (r.GetString() is string rs) required.Add(rs);

        foreach (var prop in props.EnumerateObject())
            result[prop.Name] = GenerateFromSchema(prop.Value, schemas, depth + 1);

        return result;
    }

    static List<object?> GenerateArray(JsonElement schema, Dictionary<string, JsonElement> schemas, int depth)
    {
        if (schema.TryGetProperty("items", out var items))
            return [GenerateFromSchema(items, schemas, depth + 1)];
        return [];
    }

    static string GenerateString(JsonElement schema)
    {
        if (schema.TryGetProperty("format", out var fmt))
        {
            return fmt.GetString() switch
            {
                "date-time" => DateTime.UtcNow.ToString("o"),
                "date" => DateTime.UtcNow.ToString("yyyy-MM-dd"),
                "uuid" or "guid" => Guid.NewGuid().ToString(),
                "email" => "user@example.com",
                "uri" => "https://example.com",
                "password" => "P@ssw0rd",
                _ => "string"
            };
        }

        if (schema.TryGetProperty("enum", out var en))
        {
            foreach (var e in en.EnumerateArray())
                return e.GetString() ?? "value";
        }

        return "string";
    }

    static object? ParseJsonElement(JsonElement el) => el.ValueKind switch
    {
        JsonValueKind.String => el.GetString(),
        JsonValueKind.Number => el.TryGetInt64(out long l) ? (object)l : el.GetDouble(),
        JsonValueKind.True => true,
        JsonValueKind.False => false,
        JsonValueKind.Null => null,
        _ => el.GetRawText()
    };

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    static string ResolveBaseUrl(JsonElement root)
    {
        // OpenAPI 3.x — servers array
        if (root.TryGetProperty("servers", out var servers))
        {
            foreach (var server in servers.EnumerateArray())
            {
                if (server.TryGetProperty("url", out var url))
                {
                    string u = url.GetString() ?? "";
                    if (!string.IsNullOrWhiteSpace(u)) return u;
                }
            }
        }

        // Swagger 2.x — host + basePath + schemes
        string host = root.TryGetProperty("host", out var h) ? h.GetString() ?? "localhost" : "localhost";
        string basePath = root.TryGetProperty("basePath", out var bp) ? bp.GetString() ?? "/" : "/";
        return $"https://{host}{basePath}".TrimEnd('/');
    }

    static bool HasBearerAuth(JsonElement root)
    {
        if (root.TryGetProperty("components", out var components)
            && components.TryGetProperty("securitySchemes", out var schemes))
        {
            foreach (var scheme in schemes.EnumerateObject())
            {
                if (scheme.Value.TryGetProperty("scheme", out var s) &&
                    s.GetString()?.Equals("bearer", StringComparison.OrdinalIgnoreCase) == true)
                    return true;
                if (scheme.Value.TryGetProperty("type", out var type) &&
                    type.GetString()?.Equals("apiKey", StringComparison.OrdinalIgnoreCase) == true)
                    return true;
            }
        }
        // Swagger 2.x
        if (root.TryGetProperty("securityDefinitions", out var defs))
        {
            foreach (var def in defs.EnumerateObject())
            {
                string? defType = def.Value.TryGetProperty("type", out var dt) ? dt.GetString() : null;
                if (defType is "oauth2" or "apiKey") return true;
            }
        }
        return false;
    }

    static bool IsOperationSecured(JsonElement op, JsonElement root)
    {
        // Cek security di level operasi
        if (op.TryGetProperty("security", out var sec))
            return sec.GetArrayLength() > 0;

        // Cek security global
        if (root.TryGetProperty("security", out var globalSec))
            return globalSec.GetArrayLength() > 0;

        return false;
    }

    static string GetFirstTag(JsonElement op)
    {
        if (op.TryGetProperty("tags", out var tags))
        {
            foreach (var tag in tags.EnumerateArray())
                return tag.GetString() ?? "General";
        }
        return "General";
    }

    static Dictionary<string, JsonElement> ResolveSchemas(JsonElement root)
    {
        var result = new Dictionary<string, JsonElement>(StringComparer.OrdinalIgnoreCase);

        // OpenAPI 3.x
        if (root.TryGetProperty("components", out var components)
            && components.TryGetProperty("schemas", out var schemas))
        {
            foreach (var schema in schemas.EnumerateObject())
                result[schema.Name] = schema.Value;
        }

        // Swagger 2.x
        if (root.TryGetProperty("definitions", out var defs))
        {
            foreach (var def in defs.EnumerateObject())
                result[def.Name] = def.Value;
        }

        return result;
    }

    static string FormatJson(string raw)
    {
        try
        {
            var doc = JsonDocument.Parse(raw);
            return JsonSerializer.Serialize(doc, new JsonSerializerOptions { WriteIndented = true });
        }
        catch
        {
            return raw;
        }
    }
}