// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sidata.SLIP2.Data.Context;

#nullable disable

namespace Sidata.SLIP2.Data.Context.Migrations
{
    [DbContext(typeof(LoyaltyDbContext))]
    [Migration("20260626142304_InitialBuild")]
    partial class InitialBuild
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sidata.SLIP2.Data.Definitions.InstrumentDefinition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("AllowDebit")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowNegativeBalance")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowTopup")
                        .HasColumnType("bit");

                    b.Property<byte>("BalanceStrategyType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2026, 6, 26, 14, 23, 4, 26, DateTimeKind.Utc).AddTicks(3429));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("dev-sys");

                    b.Property<string>("DefinitionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DefinitionName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("EarnConversionRate")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(20, 4)
                        .HasColumnType("decimal(20,4)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("EarnRoundingFactor")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(20, 4)
                        .HasColumnType("decimal(20,4)")
                        .HasDefaultValue(0m);

                    b.Property<byte>("EarnRoundingMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<int>("ExpireAfterDays")
                        .HasColumnType("int");

                    b.Property<bool>("HasExpiration")
                        .HasColumnType("bit");

                    b.Property<long>("InstrumentTypeId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("MaximumBalance")
                        .HasPrecision(20, 4)
                        .HasColumnType("decimal(20,4)");

                    b.Property<long>("MerchantId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("RedeemConversionRate")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(20, 4)
                        .HasColumnType("decimal(20,4)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("RedeemRoundingFactor")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(20, 4)
                        .HasColumnType("decimal(20,4)")
                        .HasDefaultValue(0m);

                    b.Property<byte>("RedeemRoundingMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<bool>("SingleUseOnly")
                        .HasColumnType("bit");

                    b.Property<bool>("Transferable")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentTypeId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("MerchantId", "DefinitionCode")
                        .IsUnique();

                    b.ToTable("InstrumentDefinition", (string)null);
                });

            modelBuilder.Entity("Sidata.SLIP2.Data.Definitions.InstrumentType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2026, 6, 26, 14, 23, 4, 29, DateTimeKind.Utc).AddTicks(532));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("dev-sys");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("TypeCode")
                        .IsUnique();

                    b.ToTable("InstrumentType", (string)null);
                });

            modelBuilder.Entity("Sidata.SLIP2.Data.Definitions.MerchantInstrumentType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2026, 6, 26, 14, 23, 4, 30, DateTimeKind.Utc).AddTicks(619));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("dev-sys");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("InstrumentTypeId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<long>("MerchantId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentTypeId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("MerchantId", "InstrumentTypeId")
                        .IsUnique();

                    b.ToTable("MerchantInstrumentType", (string)null);
                });

            modelBuilder.Entity("Sidata.SLIP2.Data.Masters.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2026, 6, 26, 14, 23, 4, 31, DateTimeKind.Utc).AddTicks(4263));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("dev-sys");

                    b.Property<string>("CustomerNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<long>("MerchantId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("SimariCustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("SimariCustomerId");

                    b.HasIndex("MerchantId", "CustomerNumber")
                        .IsUnique();

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("Sidata.SLIP2.Data.Masters.InstrumentAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ActivatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2026, 6, 26, 14, 23, 4, 32, DateTimeKind.Utc).AddTicks(6789));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("dev-sys");

                    b.Property<decimal>("CurrentBalance")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(20, 4)
                        .HasColumnType("decimal(20,4)")
                        .HasDefaultValue(0m);

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("InstrumentDefinitionId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<long>("MerchantId")
                        .HasColumnType("bigint");

                    b.Property<string>("PinHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("PinLockedUntilUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ReservedBalance")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(20, 4)
                        .HasColumnType("decimal(20,4)")
                        .HasDefaultValue(0m);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InstrumentDefinitionId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Status");

                    b.HasIndex("MerchantId", "AccountNumber")
                        .IsUnique();

                    b.ToTable("InstrumentAccount", (string)null);
                });

            modelBuilder.Entity("Sidata.SLIP2.Data.Masters.Merchant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2026, 6, 26, 14, 23, 4, 34, DateTimeKind.Utc).AddTicks(1381));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("dev-sys");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MerchantCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MerchantName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("MerchantCode")
                        .IsUnique();

                    b.ToTable("Merchant", (string)null);
                });

            modelBuilder.Entity("Sidata.SLIP2.Data.Periods.AccountSummaryPeriod", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AccountingPeriodMonth")
                        .HasColumnType("int");

                    b.Property<int>("AccountingPeriodYear")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClosedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("ClosingBalance")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(20, 4)
                        .HasColumnType("decimal(20,4)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2026, 6, 26, 14, 23, 4, 36, DateTimeKind.Utc).AddTicks(1051));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("dev-sys");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("InstrumentAccountId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsClosed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("OpeningBalance")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(20, 4)
                        .HasColumnType("decimal(20,4)")
                        .HasDefaultValue(0m);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("TotalEarnAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(20, 4)
                        .HasColumnType("decimal(20,4)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TotalExpireAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(20, 4)
                        .HasColumnType("decimal(20,4)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TotalOtherAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(20, 4)
                        .HasColumnType("decimal(20,4)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TotalRedeemAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(20, 4)
                        .HasColumnType("decimal(20,4)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentAccountId");

                    b.HasIndex("IsClosed");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("InstrumentAccountId", "AccountingPeriodYear", "AccountingPeriodMonth")
                        .IsUnique();

                    b.ToTable("AccountSummaryPeriod", (string)null);
                });

            modelBuilder.Entity("Sidata.SLIP2.Data.Periods.MerchantSummaryPeriod", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AccountingPeriodMonth")
                        .HasColumnType("int");

                    b.Property<int>("AccountingPeriodYear")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2026, 6, 26, 14, 23, 4, 37, DateTimeKind.Utc).AddTicks(2812));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("dev-sys");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<long>("MerchantId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("TotalAccountCount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(20, 4)
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalActiveAccountCount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(20, 4)
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalActiveCustomerCount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(20, 4)
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal>("TotalClosingBalance")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(20, 4)
                        .HasColumnType("decimal(20,4)")
                        .HasDefaultValue(0m);

                    b.Property<int>("TotalCustomerCount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(20, 4)
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal>("TotalEarnAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(20, 4)
                        .HasColumnType("decimal(20,4)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TotalExpireAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(20, 4)
                        .HasColumnType("decimal(20,4)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TotalOpeningBalance")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(20, 4)
                        .HasColumnType("decimal(20,4)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TotalOtherAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(20, 4)
                        .HasColumnType("decimal(20,4)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TotalRedeemAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(20, 4)
                        .HasColumnType("decimal(20,4)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("MerchantId");

                    b.HasIndex("MerchantId", "AccountingPeriodYear", "AccountingPeriodMonth")
                        .IsUnique();

                    b.ToTable("MerchantSummaryPeriod", (string)null);
                });

            modelBuilder.Entity("Sidata.SLIP2.Data.Transactions.BalanceBucket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("ConsumedAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(20, 4)
                        .HasColumnType("decimal(20,4)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2026, 6, 26, 14, 23, 4, 38, DateTimeKind.Utc).AddTicks(5390));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("dev-sys");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("EarnedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpireAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("InstrumentAccountId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("OriginalAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(20, 4)
                        .HasColumnType("decimal(20,4)")
                        .HasDefaultValue(0m);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("InstrumentAccountId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("BalanceBucket", (string)null);
                });

            modelBuilder.Entity("Sidata.SLIP2.Data.Transactions.IdempotencyRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2026, 6, 26, 14, 23, 4, 39, DateTimeKind.Utc).AddTicks(4458));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("dev-sys");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ExpireAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("IdempotencyRecordStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("RequestData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("IdempotencyKey", "RequestHash")
                        .IsUnique();

                    b.ToTable("IdempotencyRecord", (string)null);
                });

            modelBuilder.Entity("Sidata.SLIP2.Data.Transactions.LedgerTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AccountingPeriodMonth")
                        .HasColumnType("int");

                    b.Property<int>("AccountingPeriodYear")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(20, 4)
                        .HasColumnType("decimal(20,4)")
                        .HasDefaultValue(0m);

                    b.Property<string>("BranchReference")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2026, 6, 26, 14, 23, 4, 40, DateTimeKind.Utc).AddTicks(3081));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("dev-sys");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ExternalReferenceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("IdempotencyRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<long>("InstrumentAccountId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MachineReference")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("MerchantId")
                        .HasColumnType("bigint");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("TransactionDateAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("TransactionType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyRecordId");

                    b.HasIndex("InstrumentAccountId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("MerchantId", "TransactionReferenceNumber")
                        .IsUnique();

                    b.HasIndex("MerchantId", "AccountingPeriodYear", "AccountingPeriodMonth");

                    b.ToTable("LedgerTransaction", (string)null);
                });

            modelBuilder.Entity("Sidata.SLIP2.Data.Definitions.InstrumentDefinition", b =>
                {
                    b.HasOne("Sidata.SLIP2.Data.Definitions.InstrumentType", "InstrumentType")
                        .WithMany("InstrumentDefinitions")
                        .HasForeignKey("InstrumentTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Sidata.SLIP2.Data.Masters.Merchant", "Merchant")
                        .WithMany("InstrumentDefinitions")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("InstrumentType");

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("Sidata.SLIP2.Data.Definitions.MerchantInstrumentType", b =>
                {
                    b.HasOne("Sidata.SLIP2.Data.Definitions.InstrumentType", "InstrumentType")
                        .WithMany()
                        .HasForeignKey("InstrumentTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Sidata.SLIP2.Data.Masters.Merchant", "Merchant")
                        .WithMany()
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("InstrumentType");

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("Sidata.SLIP2.Data.Masters.Customer", b =>
                {
                    b.HasOne("Sidata.SLIP2.Data.Masters.Merchant", "Merchant")
                        .WithMany("Customers")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("Sidata.SLIP2.Data.Masters.InstrumentAccount", b =>
                {
                    b.HasOne("Sidata.SLIP2.Data.Masters.Customer", "Customer")
                        .WithMany("InstrumentAccounts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Sidata.SLIP2.Data.Definitions.InstrumentDefinition", "InstrumentDefinition")
                        .WithMany("InstrumentAccounts")
                        .HasForeignKey("InstrumentDefinitionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Sidata.SLIP2.Data.Masters.Merchant", "Merchant")
                        .WithMany()
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("InstrumentDefinition");

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("Sidata.SLIP2.Data.Transactions.BalanceBucket", b =>
                {
                    b.HasOne("Sidata.SLIP2.Data.Masters.InstrumentAccount", "InstrumentAccount")
                        .WithMany("BalanceBuckets")
                        .HasForeignKey("InstrumentAccountId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("InstrumentAccount");
                });

            modelBuilder.Entity("Sidata.SLIP2.Data.Transactions.LedgerTransaction", b =>
                {
                    b.HasOne("Sidata.SLIP2.Data.Masters.InstrumentAccount", "InstrumentAccount")
                        .WithMany()
                        .HasForeignKey("InstrumentAccountId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Sidata.SLIP2.Data.Masters.Merchant", "Merchant")
                        .WithMany()
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("InstrumentAccount");

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("Sidata.SLIP2.Data.Definitions.InstrumentDefinition", b =>
                {
                    b.Navigation("InstrumentAccounts");
                });

            modelBuilder.Entity("Sidata.SLIP2.Data.Definitions.InstrumentType", b =>
                {
                    b.Navigation("InstrumentDefinitions");
                });

            modelBuilder.Entity("Sidata.SLIP2.Data.Masters.Customer", b =>
                {
                    b.Navigation("InstrumentAccounts");
                });

            modelBuilder.Entity("Sidata.SLIP2.Data.Masters.InstrumentAccount", b =>
                {
                    b.Navigation("BalanceBuckets");
                });

            modelBuilder.Entity("Sidata.SLIP2.Data.Masters.Merchant", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("InstrumentDefinitions");
                });
#pragma warning restore 612, 618
        }
    }
}
